import java.io.Serializable;

public class Request implements Serializable {
    private User recipient;
    private User sender;
    private int type;

    private boolean recipientAccepted;
    private boolean senderAccepted;

    public void setType(int type) {
        this.type = type;
    }

    public Request(User from, User to, int type) {
        this.recipient = to;
        this.sender = from;
        this.type = type;
    }

    public User getRecipient() {
        return recipient;
    }

    public User getSender() {
        return sender;
    }

    public int getType() {
        return type;
    }

    public void accept(User user) {
        if(user.equals(recipient)) {
            this.recipientAccepted = true;
        }
        else {
            this.senderAccepted = true;
        }
    }

    public void deny(User user) {
        if(user.equals(recipient)) {
            this.recipientAccepted = false;
        }
        else {
            this.senderAccepted = false;
        }
    }

    public boolean isAccepted() {
        return recipientAccepted && senderAccepted;
    }

    @Override
    public boolean equals(Object o) { //Generated by Intellij
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Request request = (Request) o;
        return type == request.type &&
                recipient.equals(request.recipient) &&
                sender.equals(request.sender);
    }
}
