import java.io.Serializable;
import java.util.Objects;

public class User implements Serializable {
    private String username;
    private int id; //id of 0 means a user only on server side
    private boolean online;

    public User(int id, String username) {
        this.id = id;
        this.username = username;
    }

    public User(String username) {
        this.username = username;
        this.id = 0;
    }

    public User(int id) {
        this.id = id;
        this.username = null;
    }

    public int getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public boolean isOnline() {
        return online;
    }

    public void setOnline(boolean online) {
        this.online = online;
    }

    @Override
    public boolean equals(Object o) { //generated by Intellij
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id; //&&
                //Objects.equals(username, user.username);
    }
}
